In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("electronics_sales.csv")

df.head()

,Product,Month,Promotion,Festival_Season,Discount,Previous_Month_Sales,Sales
0,Microwave Oven,January,No,No,21,230,247
1,Smart TV,June,Yes,Yes,31,140,217
2,Water Purifier,July,No,Yes,39,110,158
3,Microwave Oven,December,Yes,No,33,45,93
4,Ceiling Fan,January,Yes,No,4,84,113

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product               2000 non-null   str
 1   Month                 2000 non-null   str
 2   Promotion             2000 non-null   str
 3   Festival_Season       2000 non-null   str
 4   Discount              2000 non-null   int64
 5   Previous_Month_Sales  2000 non-null   int64
 6   Sales                 2000 non-null   int64
dtypes: int64(3), str(4)
memory usage: 154.1 KB

In [6]:
df.shape

(2000, 7)

In [7]:
df.isnull().sum()

Product                 0
Month                   0
Promotion               0
Festival_Season         0
Discount                0
Previous_Month_Sales    0
Sales                   0
dtype: int64

In [8]:
df.describe()

          Discount  Previous_Month_Sales       Sales
count  2000.000000           2000.000000  2000.00000
mean     20.059000            132.721500   180.07250
std      11.915683             66.924737    73.87507
min       0.000000             20.000000    23.00000
25%      10.000000             73.000000   120.00000
50%      20.000000            133.000000   178.00000
75%      30.000000            191.000000   239.00000
max      40.000000            250.000000   392.00000

In [9]:
df["Product"].value_counts()

Product
Ceiling Fan        219
Washing Machine    218
Microwave Oven     215
Room Heater        207
Refrigerator       203
Laptop             202
Smart TV           194
Water Purifier     187
Air Conditioner    178
Air Cooler         177
Name: count, dtype: int64

In [10]:
df["Month"].value_counts()

Month
August       197
April        173
December     172
September    170
November     168
January      166
October      166
February     162
March        162
June         157
May          157
July         150
Name: count, dtype: int64

In [11]:
df["Promotion"].value_counts()

Promotion
No     1022
Yes     978
Name: count, dtype: int64

In [12]:
df["Festival_Season"].value_counts()

Festival_Season
No     1006
Yes     994
Name: count, dtype: int64

In [13]:
df["Sales"].describe()

count    2000.00000
mean      180.07250
std        73.87507
min        23.00000
25%       120.00000
50%       178.00000
75%       239.00000
max       392.00000
Name: Sales, dtype: float64

In [5]:
import pandas as pd

df = pd.read_csv("electronics_sales.csv")

In [6]:
ac = df[df["Product"] == "Air Conditioner"]

ac.groupby("Month")["Sales"].mean().round()

Month
April        236.0
August       214.0
December      98.0
February     115.0
January       98.0
July         237.0
June         285.0
March        181.0
May          315.0
November     102.0
October      119.0
September    150.0
Name: Sales, dtype: float64

In [7]:
heater = df[df["Product"] == "Room Heater"]

heater.groupby("Month")["Sales"].mean().round()

Month
April         94.0
August        74.0
December     315.0
February     242.0
January      298.0
July          57.0
June          60.0
March        137.0
May           64.0
November     227.0
October      146.0
September     89.0
Name: Sales, dtype: float64

In [8]:
tv = df[df["Product"] == "Smart TV"]

tv.groupby("Month")["Sales"].mean().round()

Month
April        197.0
August       189.0
December     235.0
February     172.0
January      175.0
July         193.0
June         201.0
March        171.0
May          189.0
November     267.0
October      286.0
September    226.0
Name: Sales, dtype: float64

In [9]:
ac = df[df["Product"] == "Air Conditioner"]

ac.groupby("Month")["Sales"].mean().round()

Month
April        236.0
August       214.0
December      98.0
February     115.0
January       98.0
July         237.0
June         285.0
March        181.0
May          315.0
November     102.0
October      119.0
September    150.0
Name: Sales, dtype: float64

In [4]:
import pandas as pd

df = pd.read_csv("electronics_sales.csv")

df.head()

,Product,Month,Promotion,Festival_Season,Discount,Previous_Month_Sales,Demand_Factor,Sales
0,Air Conditioner,January,No,Yes,39,201,0.641,129
1,Air Conditioner,April,Yes,Yes,35,122,1.276,156
2,Air Cooler,October,No,No,9,210,0.478,100
3,Room Heater,September,Yes,No,4,174,0.570,99
4,Smart TV,May,Yes,No,39,92,1.209,111

In [5]:
df.columns

Index(['Product', 'Month', 'Promotion', 'Festival_Season', 'Discount',
       'Previous_Month_Sales', 'Demand_Factor', 'Sales'],
      dtype='str')

In [6]:
ac = df[df["Product"] == "Air Conditioner"]

ac.groupby("Month")["Demand_Factor"].mean().round(2)

Month
April        1.21
August       1.20
December     0.61
February     0.72
January      0.61
July         1.32
June         1.48
March        1.04
May          1.55
November     0.63
October      0.85
September    1.02
Name: Demand_Factor, dtype: float64

In [7]:
heater = df[df["Product"] == "Room Heater"]

heater.groupby("Month")["Demand_Factor"].mean().round(2)

Month
April        0.64
August       0.45
December     1.51
February     1.36
January      1.48
July         0.41
June         0.45
March        0.94
May          0.45
November     1.32
October      0.87
September    0.65
Name: Demand_Factor, dtype: float64

In [8]:
tv = df[df["Product"] == "Smart TV"]

tv.groupby("Month")["Demand_Factor"].mean().round(2)

Month
April        1.17
August       1.28
December     1.42
February     1.03
January      1.07
July         1.20
June         1.22
March        1.11
May          1.14
November     1.49
October      1.52
September    1.34
Name: Demand_Factor, dtype: float64